### ISSUE TITLE
Suggestion for merging this repository to the outdated main ros executive_smach repository

### ISSUE THREAD

**Issue by JaehyunShim** [tue-robotics/executive_smach#4]
Hi @tue-robotics-robots,

This Smach repository worked for me without any issues in the ROS Melodic environment. 
Thank you for the great work. 
The current main branch hasn't been updated for long as you can see at the [link](https://github.com/ros/executive_smach)
Why don't you PR this branch to the main branch so more open source users can use it? 

Ryan

**Comment by JaehyunShim** [comment]
ping @tue-robotics-robots

**Comment by JaehyunShim** [comment]
ping @Rayman @LoyVanBeek

**Comment by LoyVanBeek** [comment]
Mostly a time issue. We just haven't taken the effort but could be worth it indeed.

**Comment by JaehyunShim** [comment]
@LoyVanBeek 

I tested this package works fine. The only thing to be done now is to send a PR to the main repository

**Comment by Rayman** [comment]
@JaehyunShim the development for the upstream smach_ros repository has been stopped I think. I've send a PR in may but haven't had a single reaction: https://github.com/ros/executive_smach/pull/73

**Comment by LoyVanBeek** [comment]
Also, the differences between this repo and upstream are not trivial. Splitting that up properly so that I myself would even look at as a PR requires more time then I can currently put into it. The slim chances of merging do not help either.

**Comment by JaehyunShim** [comment]
Thank you. I will test if their latest noetic release works first. I will close this issue.
